---
- name: Install Docker 
  hosts: web
  become: true
  vars:
    docker_compose_version: "1.29.2"
  tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=yes cache_valid_time=3600
    - name: Update all apt packages
      ansible.builtin.apt: upgrade=yes
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add apt repository for stable Docker
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ansible_user}}"
        groups: docker
        append: true
    - name: Download docker-compose {{ docker_compose_version }}
      ansible.builtin.get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'
    - name: Check docker-compose exists
      ansible.builtin.stat: path=~/docker-compose
      register: docker_compose
    - name: Move docker-compose to /usr/local/bin/docker-compose
      ansible.builtin.command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists