---
- name: Setup Nginx Reverse Proxy
  hosts: web
  become: false
  tasks:
    - name: Ensure required Docker SDK is installed
      ansible.builtin.pip:
        name: docker-compose
    - name: Copy configuration files and certificate to server
      ansible.builtin.copy:
        src: ./nginx/{{ item }}
        dest: /home/{{ ansible_user }}/nginx/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - public_files
        - nginx.conf
        - docker-compose.yml
        - cert.key
        - cert.pem
    - name: Launch server
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/nginx
        state: present
        restarted: true