---
- name: Launch Portfolio Server
  hosts: web
  become: false
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt: update_cache=yes cache_valid_time=3600
    - name: Update all apt packages
      become: true
      ansible.builtin.apt: upgrade=yes
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name: git
        state: present
    - name: Clone portfolio repository
      ansible.builtin.git:
        repo: "https://github.com/southball/portfolio-rails"
        dest: /home/{{ ansible_user }}/portfolio-rails
        force: true
    - name: Copy master.key to server  
      ansible.builtin.copy:
        src: ./portfolio/master.key
        dest: /home/{{ ansible_user }}/portfolio-rails/config
    - name: Launch portfolio container
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/portfolio-rails
        state: present
        build: true
        restarted: true
      environment:
        PORT: 10002