version: '3'
services:
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1-amd64
    container_name: oauth2-proxy
    restart: always
    ports:
      - "${PORT-80}:8080"
    command: 
      - "--config=/etc/oauth2-proxy.cfg"
      - "--cookie-secret=${COOKIE_SECRET}"
      - "--client-id=${CLIENT_ID}"
      - "--client-secret=${CLIENT_SECRET}"
      - "--google-group=${GOOGLE_GROUP}"
      - "--google-admin-email=${GOOGLE_ADMIN_EMAIL}"
      - "--redirect-url=${REDIRECT_URL}"
      - "--google-service-account-json=/etc/google-service-account.json"
      - "--email-domain=*"
    volumes:
      - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
      - ./google-service-account.json:/etc/google-service-account.json
    extra_hosts:
      - "host.docker.internal:host-gateway"